### ISSUE TITLE
TypeError: Class constructor a cannot be invoked without 'new'

### ISSUE THREAD

**Issue by rodrigok** [Adornis/typescript#3]
When trying this module to start converting my app I received the error:

```
W20190128-10:41:04.388(-2)? (STDERR) TypeError: Class constructor a cannot be invoked without 'new'
W20190128-10:41:04.388(-2)? (STDERR)     at new b (rocketchat_models/server/models/b.ts:3:1)
W20190128-10:41:04.388(-2)? (STDERR)     at b.js (rocketchat_models/server/models/b.ts:9:16)
W20190128-10:41:04.388(-2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
...
```

The file for the test is:
```typescript
import { a } from './a';

export class b extends a {
	b() {

	}
}

export default new b();
```

Importing a JS file:
```javascript
export class a {
	a() {

	}
}
```

And the compilations result seems to be:
```javascript
///.meteor/local/build/programs/server/packages/rocketchat_models.js
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                  //
// packages/rocketchat_models/server/models/a.js                                                                    //
//                                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                    //
module.export({
  a: () => a
});

class a {
  a() {}

}
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

},"b.ts":function(require,exports,module){

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                  //
// node_modules/meteor/rocketchat_models/server/models/b.ts                                                         //
//                                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                    //
module.link("./b.js", { "*": "*+" });

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

},"b.js":function(require,exports){

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                  //
// packages/rocketchat_models/server/models/b.js                                                                    //
//                                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                    //
Object.defineProperty(exports, "__esModule", { value: true });
var a_1 = require("./a");
var b = /** @class */ (function (_super) {
    __extends(b, _super);
    function b() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    b.prototype.b = function () {
    };
    return b;
}(a_1.a));
exports.b = b;
exports.default = new b();

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
```

**Comment by yorrd** [comment]
@rodrigok not having looked at your specific example in depth yet, are you sure this is a problem of this package? Does it work with `barbatus:typescript`?

**Comment by yorrd** [comment]
closing this for now, let me know if it has to do with this package!
